### ISSUE TITLE
v1.0.2: HessTest2 fails on some more exotic architectures 

### ISSUE THREAD

**Issue by junghans** [robashaw/libecpint#14] opened 2020-10-03 19:50 UTC
The HessTest2 fails on aarch64, ppc64le, s390x.

Details
[build_aarch64.txt](https://github.com/robashaw/libecpint/files/5322245/build_aarch64.txt)
[build_ppc64le.txt](https://github.com/robashaw/libecpint/files/5322248/build_ppc64le.txt)
[build_s390x.txt](https://github.com/robashaw/libecpint/files/5322249/build_s390x.txt)

i686, x86_64 snd armv7hl works perfectly.
(from https://koji.fedoraproject.org/koji/taskinfo?taskID=52711488)

**Comment by junghans** [comment] 2020-10-03 20:28
on openSUSE that test fails on i586 as well: 
[opensuse_build_i586.txt](https://github.com/robashaw/libecpint/files/5322281/opensuse_build_i586.txt)

**Comment by robashaw** [comment] 2020-10-04 06:15
Looking at the logs you've provided (thanks for another detailed report), the issue is purely numerical, in that the derivatives are disagreeing on the order of 10^-5. 

This could be absolutely fine, I don't personally have enough experience of how stable Hessians are with respect to the numerics of integrals - in which case, the test could be fixed by changing the numerical tolerance. If this level of discrepancy is a problem, however, then it is an architecture thing that I have absolutely no expertise to deal with. 

Actions to resolve:
* I will consult someone who knows more than me and maybe run some frequency calculation stability tests
* I will also add a note to the documentation with regards to this specific test

Given the above, this issue likely won't be resolved for a while.

**Comment by junghans** [comment] 2020-10-04 13:19
On Gentoo (https://bugs.gentoo.org/746440) same test fails on amd64 (x86_64) as well.
[gentoo_build_amd64.txt](https://github.com/robashaw/libecpint/files/5323265/gentoo_build_amd64.txt)
[gentoo_test_log.xt.txt](https://github.com/robashaw/libecpint/files/5323266/gentoo_test_log.xt.txt)

**Comment by robashaw** [comment] 2020-12-11 19:00
I have adjusted the precision of this test to now be at a threshold where calculated frequencies are unaffected (PR #23). This should prevent numerical issues on different architectures - please open a new issue if this turns out to not be the case.

**Closed by robashaw** 2020-12-11 19:00 UTC
Labels: help wanted
